sudo: required

services:
  - docker

before_install:
  - docker build -t anamip/kwaa -f ./client/Dockerfile.dev ./client


script:
  - docker run anamip/kwaa npm test -- --coverage

after_success:
  - docker build -t anamip/multi-client -f ./client
  - docker build -t anamip/multi-nginx -f ./nginx 
  - docker build -t anamip/multi-server -f ./server
  - docker build -t anamip/multi-worker -f ./worker

  # login to Docker cli

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --passwod-stdin

  #take those images and push them to docker hub
  
  - docker push anamip/multi-client
  - docker push anamip/multi-nginx
  - docker push anamip/multi-server
  - docker push anamip/multi-worker


